### ISSUE TITLE
Errors prevented startup: boilerplate_web.browser.html:1: Expected one of: <body>,    <head>, <template>

### ISSUE THREAD

**Issue by mexin** [nolandg/meteor-boilerplate-generator#1]
I'm getting this error 

```
Errors prevented startup:
   
   While processing files with templating-compiler (for target web.browser):
   boilerplate-gen/boilerplate_web.browser.html:1: Expected one of: <body>,
   <head>, <template>
   boilerplate-gen/boilerplate_web.cordova.html:1: Expected one of: <body>,
   <head>, <template>
```

Did I missed something?

Thanks!

**Comment by nolandg** [comment]
Are you using the latest build?

It looks like there's a typo or something near the top of the html template. Open that file in a highlighting editor and look for syntax screw ups. The current build is working for me.

**Comment by nolandg** [comment]
What Meteor version? I've only tested this against 1.4.2. Maybe the templating engine is different?

**Comment by mexin** [comment]
Thanks for the fast reply @nolandg, I'm on METEOR@1.4.2.3, Just checked for typos and everything seems fine.

One more question, on the readme you wrote that we should copy the download zip, to "any" directory, this should be inside my meteor project? or any recommendations?

Thanks!

**Comment by nolandg** [comment]
It needs to be in the METEOR_PACKAGE_DIRS directory. This should be outside of the your project. Pick a directory, set the env variable METEOR_PACKAGE_DIRS to that directory, and unzip there.

You can check that Meteor is building with this package instead of the default core version of it by removing this package and seeing if the error goes away.
